### ISSUE TITLE
window.__screener_storybook__ doesn't exist

### ISSUE THREAD

**Issue by benkeen** [screener-io/screener-storybook#154]
Hi! I'm encountering a persistent error on our CI, where it complains that `window.__screener_storybook__` doesn't exist - full error log below. Locally it's working fine, but I haven't been able to figure out what could be causing it on the CI. Any tips for debugging?

```

2022-11-18T22:46:17.3629681Z ╭─────────────────────────────────────────────────────────────────────╮
2022-11-18T22:46:17.3630144Z │                                                                     │
2022-11-18T22:46:17.3630600Z │   Storybook 6.5.12 for React started                                │
2022-11-18T22:46:17.3631024Z │   21 s for manager and 43 s for preview                             │
2022-11-18T22:46:17.3631389Z │                                                                     │
2022-11-18T22:46:17.3632129Z │   Local:            http://localhost:2000/                          │
2022-11-18T22:46:17.3632867Z │   On your network:  http://10.244.152.3:2000/                       │
2022-11-18T22:46:17.3633525Z │                                                                     │
2022-11-18T22:46:17.3634173Z │   A new version (6.5.13) is available!                              │
2022-11-18T22:46:17.3634559Z │                                                                     │
2022-11-18T22:46:17.3634938Z │   Upgrade now: npx storybook@latest upgrade                         │
2022-11-18T22:46:17.3635304Z │                                                                     │
2022-11-18T22:46:17.3635655Z │   Read full changelog:                                              │
2022-11-18T22:46:17.3636097Z │   https://github.com/storybookjs/storybook/blob/next/CHANGELOG.md   │
2022-11-18T22:46:17.3636500Z │                                                                     │
2022-11-18T22:46:17.3636868Z ╰─────────────────────────────────────────────────────────────────────╯
2022-11-18T22:46:17.3637116Z DEBUG: previewRoute /iframe.html
2022-11-18T22:46:17.3637427Z DEBUG: GET http://localhost:2000/iframe.html
2022-11-18T22:46:17.3637766Z webpack built preview 415f28cd4bfeeb1e726d in 1634ms
2022-11-18T22:46:17.3638051Z DEBUG: getStorybook 0
2022-11-18T22:46:17.3638305Z DEBUG: config.storybookPort 2000
2022-11-18T22:46:18.2312733Z Update this package.json to use a subpath pattern like "./*".
2022-11-18T22:46:18.2313673Z (Use `node --trace-deprecation ...` to show where the warning was created)
2022-11-18T22:46:18.2314114Z info Addon-docs: using MDX1
2022-11-18T22:46:18.2314379Z info => Using implicit CSS loaders
2022-11-18T22:46:18.2314608Z info
2022-11-18T22:46:18.2314970Z => Loading custom Webpack config (full-control mode).
2022-11-18T22:46:18.2315272Z info => Loading custom manager config
2022-11-18T22:46:18.2315740Z <i> [webpack-dev-middleware] wait until bundle finished
2022-11-18T22:46:18.2316113Z info => Ignoring cached manager due to change in manager config
2022-11-18T22:46:18.2316551Z <i> [webpack-dev-middleware] wait until bundle finished
2022-11-18T22:46:18.2316992Z <i> [webpack-dev-middleware] wait until bundle finished: /
2022-11-18T22:46:18.2317414Z DEBUG: getStorybook Error: Evaluation failed: TypeError: window.__screener_storybook__ is not a function
2022-11-18T22:46:18.2317845Z     at __puppeteer_evaluation_script__:1:8
2022-11-18T22:46:18.2318358Z     at ExecutionContext.evaluateHandle (/vsts/_work/7/s/common/temp/node_modules/.pnpm/puppeteer@1.17.0/node_modules/puppeteer/lib/ExecutionContext.js:80:15)
2022-11-18T22:46:18.2318927Z     at processTicksAndRejections (node:internal/process/task_queues:96:5)
2022-11-18T22:46:18.2319486Z     at async ExecutionContext.evaluate (/vsts/_work/7/s/common/temp/node_modules/.pnpm/puppeteer@1.17.0/node_modules/puppeteer/lib/ExecutionContext.js:48:20)
2022-11-18T22:46:18.2320011Z   -- ASYNC --
2022-11-18T22:46:18.2320421Z     at ExecutionContext.<anonymous> (/vsts/_work/7/s/common/temp/node_modules/.pnpm/puppeteer@1.17.0/node_modules/puppeteer/lib/helper.js:110:27)
2022-11-18T22:46:18.2321055Z     at ExecutionContext.evaluate (/vsts/_work/7/s/common/temp/node_modules/.pnpm/puppeteer@1.17.0/node_modules/puppeteer/lib/ExecutionContext.js:48:31)
2022-11-18T22:46:18.2321922Z     at ExecutionContext.<anonymous> (/vsts/_work/7/s/common/temp/node_modules/.pnpm/puppeteer@1.17.0/node_modules/puppeteer/lib/helper.js:111:23)
2022-11-18T22:46:18.2322527Z     at DOMWorld.evaluate (/vsts/_work/7/s/common/temp/node_modules/.pnpm/puppeteer@1.17.0/node_modules/puppeteer/lib/DOMWorld.js:112:20)
2022-11-18T22:46:18.2323043Z     at processTicksAndRejections (node:internal/process/task_queues:96:5)
2022-11-18T22:46:18.2323475Z   -- ASYNC --
2022-11-18T22:46:18.2323878Z     at Frame.<anonymous> (/vsts/_work/7/s/common/temp/node_modules/.pnpm/puppeteer@1.17.0/node_modules/puppeteer/lib/helper.js:110:27)
2022-11-18T22:46:18.2324450Z     at Page.evaluate (/vsts/_work/7/s/common/temp/node_modules/.pnpm/puppeteer@1.17.0/node_modules/puppeteer/lib/Page.js:782:43)
2022-11-18T22:46:18.2325120Z     at Page.<anonymous> (/vsts/_work/7/s/common/temp/node_modules/.pnpm/puppeteer@1.17.0/node_modules/puppeteer/lib/helper.js:111:23)
2022-11-18T22:46:18.2325902Z     at getStorybook (/vsts/_work/7/s/common/temp/node_modules/.pnpm/screener-storybook@0.23.0/node_modules/screener-storybook/src/storybook.js:42:15)
2022-11-18T22:46:18.2326679Z     at /vsts/_work/7/s/common/temp/node_modules/.pnpm/screener-storybook@0.23.0/node_modules/screener-storybook/src/storybook.js:114:20
2022-11-18T22:46:18.2327200Z     at processTicksAndRejections (node:internal/process/task_queues:96:5)
2022-11-18T22:46:18.2327547Z Error getting Storybook object
2022-11-18T22:46:18.2327831Z Please send debug output to help@saucelabs.com
2022-11-18T22:46:18.2328132Z DEBUG: Error: Storybook object not found
2022-11-18T22:46:18.2328819Z     at Object.exports.get [as getStorybook] (/vsts/_work/7/s/common/temp/node_modules/.pnpm/screener-storybook@0.23.0/node_modules/screener-storybook/src/storybook.js:312:11)
2022-11-18T22:46:18.2329609Z     at /vsts/_work/7/s/common/temp/node_modules/.pnpm/screener-storybook@0.23.0/node_modules/screener-storybook/src/cli.js:47:40
2022-11-18T22:46:18.2330162Z     at tryCatcher (/vsts/_work/7/s/common/temp/node_modules/.pnpm/bluebird@3.4.7/node_modules/bluebird/js/release/util.js:16:23)
2022-11-18T22:46:18.2330777Z     at Promise._settlePromiseFromHandler (/vsts/_work/7/s/common/temp/node_modules/.pnpm/bluebird@3.4.7/node_modules/bluebird/js/release/promise.js:510:31)
2022-11-18T22:46:18.2331411Z     at Promise._settlePromise (/vsts/_work/7/s/common/temp/node_modules/.pnpm/bluebird@3.4.7/node_modules/bluebird/js/release/promise.js:567:18)
2022-11-18T22:46:18.2332035Z     at Promise._settlePromise0 (/vsts/_work/7/s/common/temp/node_modules/.pnpm/bluebird@3.4.7/node_modules/bluebird/js/release/promise.js:612:10)
2022-11-18T22:46:18.2332803Z     at Promise._settlePromises (/vsts/_work/7/s/common/temp/node_modules/.pnpm/bluebird@3.4.7/node_modules/bluebird/js/release/promise.js:691:18)
2022-11-18T22:46:18.2333422Z     at Promise._fulfill (/vsts/_work/7/s/common/temp/node_modules/.pnpm/bluebird@3.4.7/node_modules/bluebird/js/release/promise.js:636:18)
2022-11-18T22:46:18.2333980Z     at /vsts/_work/7/s/common/temp/node_modules/.pnpm/bluebird@3.4.7/node_modules/bluebird/js/release/nodeback.js:42:21
2022-11-18T22:46:18.2334718Z     at /vsts/_work/7/s/common/temp/node_modules/.pnpm/screener-storybook@0.23.0/node_modules/screener-storybook/src/storybook.js:299:7
2022-11-18T22:46:18.2335472Z     at done (/vsts/_work/7/s/common/temp/node_modules/.pnpm/screener-storybook@0.23.0/node_modules/screener-storybook/src/storybook.js:99:11)
2022-11-18T22:46:18.2335947Z ---

```

**Comment by sauce-tartar** [comment]
Hello @benkeen !  This _sounds like_ your build is not getting the "hook" we add via the `preview.js`

You might be able to confirm this by cat'ing the `.storybook/preview.js (or .ts)` file before you call screener-storybook.

If it helps, this is what Node is seeing at runtime for this:

```
path.resolve(process.cwd(), storybookConfigDir, 'preview.js');
```

and the `storybookConfigDir` comes from the `screener.config.js` looking something like `storybookConfigDir: '.storybook',`

_p.s. an upcoming alpha will do this differently, finding the .storybook dir on it's own without needing this additional config_

**Comment by benkeen** [comment]
Marvellous, thanks for the tips, @sauce-tartar! I'll take another look at this tomorrow.

**Comment by sauce-tartar** [comment]
We have at least 3 reports of related / similar issues now.

@benkeen would you be so kind as to share your:
* Storybook version
* any features enabled, or simply the contents of `.storybook/main.js`

**Comment by benkeen** [comment]
Hey! Sure, we're on storybook ~6.5.10, screener-storybook: ~0.23.0.

**main.js:**

```
module.exports = {
  stories: ['../../src/**/*.story.tsx'],
  addons: [
    '@storybook/addon-docs',  // 6.5.12
    '@storybook/addon-knobs', // 6.4.0
    '@storybook/addon-a11y', // 6.5.12
    '@storybook/addon-actions', // 6.5.12
    'storybook-addon-designs', // 6.2.1
  ],
  framework: '@storybook/react', // 6.5.12
  typescript: {
    check: false,
  },
  core: {
    builder: {
      name: 'webpack5',
      options: {
        lazyCompilation: true,
        fsCache: true,
      },
    },
    disableTelemetry: true,
  },
  features: {
    /*
     * Enables split bundles for faster start. Re-enable once supported by Screener:
     * https://github.com/screener-io/screener-storybook/issues/147
     */
    storyStoreV7: false,
  },
};
```

I examined the `storybookConfigDir` path as suggested and that looks correct. I also tried hacking our preview.js file (which is used if config.js isn't defined) to manually add in the injected window.__screener_storybook__ content, but same error. One possibility is that it's a permissions issue and that on our particular build agent it's forbidding overwriting that file, but it kinda seemed like a stretch... other tasks alter + create files. At this stage I'm going to wait to speak to our DevOps on Mon + see if they can shed some light.

**Comment by benkeen** [comment]
Hey @sauce-tartar, just FYI I (sort of) got to the bottom of this. 

In our repo we were referencing `7.0.0-alpha.1` of `@storybook/addons`. As mentioned above, it didn't cause any local problems - screener-storybook ran just fine - but on the CI it clunked out, with the error message posted. Hope this helps.

**Comment by sauce-tartar** [comment]
@benkeen yes that makes sense now.  We're seeing some cases where even though `storyStoreV7` is not selected, there is some drift that results in a runtime that has this new architecture.

We've been able to remove the `window.__screener_storybook__` hook completely for 0.25 which will be a step toward V7 support, providing for `storyStoreV7`.
