### ISSUE TITLE
Element type is invalid: expected a string (for built-in components) or a class/function

### ISSUE THREAD

**Issue by micahgodbolt** [screener-io/screener-storybook#31]
With typescript enabled I get this error when trying to use the Screener component in my storybook story. 

```
Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in.
Invariant Violation: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in.
    at invariant (http://localhost:5555/static/preview.bundle.js:1049:15)
    at instantiateReactComponent (http://localhost:5555/static/preview.bundle.js:12187:23)
    at instantiateChild (http://localhost:5555/static/preview.bundle.js:26079:28)
    at http://localhost:5555/static/preview.bundle.js:26106:16
    at traverseAllChildrenImpl (http://localhost:5555/static/preview.bundle.js:12473:5)
    at traverseAllChildren (http://localhost:5555/static/preview.bundle.js:12568:10)
    at Object.instantiateChildren (http://localhost:5555/static/preview.bundle.js:26105:7)
    at ReactDOMComponent._reconcilerInstantiateChildren (http://localhost:5555/static/preview.bundle.js:25767:41)
    at ReactDOMComponent.mountChildren (http://localhost:5555/static/preview.bundle.js:25806:27)
    at ReactDOMComponent._createInitialChildren (http://localhost:5555/static/preview.bundle.js:24118:32)
```

**Comment by loyalchow** [comment]
@micahgodbolt this should be resolved in v0.8.11
